version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.3
    environment:
      MYSQL_ROOT_PASSWORD: decoupled
      MYSQL_DATABASE: decoupled
      MYSQL_USER: decoupled
      MYSQL_PASSWORD: decoupled
    volumes:
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - /var/www/html/react-drupal/db:/var/lib/mysql # I want to manage volumes manually.

  php:
# 1. Images with vanilla Drupal – wodby/drupal:[DRUPAL_VERSION]-[PHP_VERSION]-[STABILITY_TAG].
#    image: wodby/drupal:8-7.1-2.4.4
#    image: wodby/drupal:8-7.0-2.4.4
#    image: wodby/drupal:7-7.1-2.4.4
#    image: wodby/drupal:7-7.0-2.4.4
#    image: wodby/drupal:7-5.6-2.4.4
#    image: wodby/drupal:6-5.6-2.4.4
#    image: wodby/drupal:6-5.3-2.4.4
# 2. Images without Drupal – wodby/drupal-php:[PHP_VERSION]-[STABILITY_TAG].
    image: wodby/drupal-php:7.1-2.4.3
#    image: wodby/drupal-php:7.0-2.4.3
#    image: wodby/drupal-php:5.6-2.4.3
#    image: wodby/drupal-php:5.3-2.4.3
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: decoupled
      DB_PASSWORD: decoupled
      DB_NAME: decoupled
      DB_DRIVER: mysql
      # PHP_XDEBUG: 1
      # PHP_XDEBUG_DEFAULT_ENABLE: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
      - /var/www/html/react-drupal/d8:/var/www/html
# Options for macOS users (http://docs.docker4drupal.org/en/latest/macos)
#      - codebase:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync

  nginx:
# wodby/drupal-nginx:[DRUPAL_VERSION]-[NGINX_VERSION]-[STABILITY_TAG].
    image: wodby/drupal-nginx:8-1.13-2.4.2
#    image: wodby/drupal-nginx:7-1.13-2.4.2
#    image: wodby/drupal-nginx:6-1.13-2.4.2
#    image: wodby/drupal-nginx:8-1.12-2.4.2
#    image: wodby/drupal-nginx:7-1.12-2.4.2
#    image: wodby/drupal-nginx:6-1.12-2.4.2
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
    volumes:
      - /var/www/html/react-drupal/d8:/var/www/html
# Options for macOS users (http://docs.docker4drupal.org/en/latest/macos)
#      - codebase:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync
    labels:
      - 'traefik.backend=nginxdecopled'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:d8.decoupled.localhost'

#  apache:
#    image: wodby/drupal-apache:2.4-1.0.2
#    depends_on:
#      - php
#    environment:
#      APACHE_LOG_LEVEL: debug
#      APACHE_BACKEND_HOST: php
#      APACHE_SERVER_ROOT: /var/www/html/web
#    volumes:
#      - codebase:/var/www/html
## Options for macOS users (http://docs.docker4drupal.org/en/latest/macos)
##      - codebase:/var/www/html:cached # User-guided caching
##      - docker-sync:/var/www/html # Docker-sync
#    labels:
#      - 'traefik.backend=apache'
#      - 'traefik.port=80'
#      - 'traefik.frontend.rule=Host:drupal.docker.localhost'

#  redis:
#    image: wodby/redis:3.2-2.1.2

#  adminer:
#    image: wodby/adminer:4.3-1.1.0
#    environment:
#      ADMINER_SALT: adminer-salt
#    labels:
#      - 'traefik.backend=adminer'
#      - 'traefik.port=9000'
#      - 'traefik.frontend.rule=Host:adminer.drupal.docker.localhost'

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: decoupled
      PMA_PASSWORD: decoupled
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=pmadecoupled'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:pma.d8.decoupled.localhost'

#  mailhog:
#    image: mailhog/mailhog
#    labels:
#      - 'traefik.backend=mailhog'
#      - 'traefik.port=8025'
#      - 'traefik.frontend.rule=Host:mailhog.drupal.hdfc'

  nodejs:
    image: wodby/drupal-node:1.0-1.0.0
    environment:
       NODE_SERVICE_KEY: node-service-key
    labels:
      - 'traefik.backend=reactjs'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:reactjs.d8.decoupled.localhost'
    volumes:
      - /var/www/html/react-drupal/react:/app
    command: sh -c 'npm install && npm run start'

  node:
    image: node:alpine
    working_dir: /app
    labels:
      - 'traefik.backend=node'
      - 'traefik.port=3000'
      - 'traefik.frontend.rule=Host:front.d8.decoupled.localhost'
    expose:
      - "3000"
    volumes:
      - /var/www/html/react-drupal/react:/app
    command: sh -c 'npm install && npm run start'

#  memcached:
#    image: wodby/memcached:1.4-2.0.0

#  rsyslog:
#    image: wodby/rsyslog

#  athenapdf:
#    image: arachnysdocker/athenapdf-service
#    environment:
#      WEAVER_AUTH_KEY: weaver-auth-key
#      WEAVER_ATHENA_CMD: "athenapdf -S"
#      WEAVER_MAX_WORKERS: 10
#      WEAVER_MAX_CONVERSION_QUEUE: 50
#      WEAVER_WORKER_TIMEOUT: 90
#      WEAVER_CONVERSION_FALLBACK: false

  portainer:
    image: portainer/portainer
    command: --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainerdecoupled'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainerdecoupled.d8.decoupled.localhost'

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
#      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  codebase:
## Docker-sync for macOS users
#  docker-sync:
#    external: true
